export const baseTechnologyToolNames = [
  "Microsoft",
  "LuxFlow",
  "Siigo Contai",
  "Siigo Nominai",
  "Siigo Facturación",
  "Intranet",
  "Universidad Pinares",
  "SharePoint - Microsoft",
  "Fudo",
  "Zebra",
  "IVMS 4600",
  "IVMS 4200",
  "Canva",
  "SIIS",
  "Coco",
  "Kommo",
  "Google",
  "Whatsapp",
  "WonderShare",
  "App Ingeniería Clínica",
  "Sitrad",
  "Equipos Biomédicos"
] as const;
